### ISSUE TITLE
//TODO:

### ISSUE THREAD

**Issue by Dynious** [Dynious/RefinedRelocation#150]
- [x] Add more modules and investigate the possibility of auto-combining modules
- [ ] Add Fluid Relocators, should also have a modular design and should be able to transport multiple fluid types in the same pipe.
- [x] Enhance Filtering, the filtering GUI should have +-4 tabs/windows/places where you should be able to pick a type of filtering (name filter/creative tab filter/pre-set filter/item filter etc.). Very, very bad mockup:
![mockup](https://cloud.githubusercontent.com/assets/3618217/3409284/aa1d87ba-fdd6-11e3-8d16-5eee905be7a9.png)

This is enough for now, I have more ideas, but I don't want to just spit everything out ;)

**Comment by blay09** [comment]
Closed since Fluid Relocators are the only thing left here and #163 has those.
