### ISSUE TITLE
TODO: Last 1.6 Issue Fixing List

### ISSUE THREAD

**Issue by Micky2506** [Dynious/RefinedRelocation#180]
- [ ] Blocked sneaky extraction module **I don't agree with this :(**
  - [ ]  If this is not required because of multi modules, I think the block extraction module should really also be removed.
- [ ]  Block extenders will not act as a inventory if placed on a machine that cannot accept inputs on that side, even if other sides are valid destinations.
  - [ ]  When a side of a machine becomes a valid destination, the block extender will not update surrounding blocks - a block update is required for relocators to connect.
- [x]  Advanced block extender tooltip only mentions insertion, but I (believe and hope) that they also work for extraction.
- [ ]  If at all possible, we should display the icon of the side of the block we push into with the sneaky buttons.
- [ ]  Might just be me, but I think the power limiters are broken once more. (tested with RF) **Not sure whats wrong, it works here! (IC2)**
- [ ]  Sneaky buttons display flipped directions **This is not the case?** (See F3, it shows north when facing north, but the module (while displaying the right direction, it will insert into the flipped side. Tested with TE machines).
-  [x] Toolbox displays Available Wrenches message when no wrenches are available, should probably display nothing (or shift right click to add ...)
-  [ ] Item detector module does not change texture in game, even though the code (I think) changes the texture. **It does for me!** (Might be a speed issue)
-  [ ] Item detector module when emitting strong redstone signal does not update the redstone through blocks.
- [ ]  Multi module is not displayed in WAILA, probably should be.
  -  [ ] WAILA module should probably be rewritten so as to have modules show like stuffed items.
- [ ]  Right clicking a multi module on an existing module should (ideally) add the multimodule onto the current module, merging them.
- [ ]  Pick item (middle click) on a module should get that module from creative, not the relocator. (more of a preference.. configuration?)
- [ ]  Redstone dust near a item detector module sometimes turns on when no items are present. This will also flip one way modules.
- [ ]  When showing stuffed items in WAILA, and the stack size exceeds 1000, the number goes outside of WAILA's box.
- [ ]  Players fall through relocators. (Should _NOT_ be a FMP bug, as this happens in 1.7 without FMP installed). **Vanilla bug**
-  [x] Seconds between each item in stuffed items should be configurable.
- [x]  Clicking on a stuffed item relocator in creative will not drop the items, and will break the relocator. (This shouldn't drop items, anyway, if we have access to EntityPlayer who clicked the stuffed items and the player is in creative).

@Dynious: This is just a start, but it is already a fairly large list, so I'd thought I would open it so you/I can get started on them. I'll mark any of these done when either I or you finish fixing them. (I need to get 1.6 dev setup if I am to fix any of these, please tell me if you want that to happen.)

Should probably also fix up the rest of the other issues.
